apiVersion: v1alpha
kind: xcuitest
sauce:
  region: eu-central-1
  concurrency: 1
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA

xcuitest:
  app: $AC_TEST_IPA_PATH
  testApp: $AC_UITESTS_RUNNER_PATH

suites:
  - name: "xcuitest"
    devices:
      - name: "iPhone 11"
        options:
          # If set, only devices with a SIM card will be queried.
          carrierConnectivity: false
          private: false
artifacts:
  download:
    when: always
    match:
      - "junit.xml"
    directory: ./artifacts/

reporters:
  spotlight: # Prints an overview of failed or otherwise interesting jobs.
    enabled: true
